In [38]:
# import data
# try 1 data set first
import pandas as pd
pd.set_option('display.max_rows', None)

# can change the file name (refer to files folder)
df = pd.read_excel("./files/2022-23_T2.xlsx")

In [39]:
# check head
print(df.head())
print("")
# check if columns are there
for column in df.columns:
    print("Column Name:",column)

             Term                   Session     Bidding Window Course Code  \
0  2022-23 Term 2  Regular Academic Session  Round 2A Window 3     ACCT101
1  2022-23 Term 2  Regular Academic Session  Round 2A Window 3     ACCT101
2  2022-23 Term 2  Regular Academic Session  Round 2A Window 3     ACCT101
3  2022-23 Term 2  Regular Academic Session  Round 2A Window 3     ACCT101
4  2022-23 Term 2  Regular Academic Session  Round 2A Window 3     ACCT101

            Description Section  Vacancy  Opening Vacancy  \
0  Financial Accounting      G1       45               45
1  Financial Accounting     G10       45               45
2  Financial Accounting     G11       45               45
3  Financial Accounting     G12       45               45
4  Financial Accounting      G2       45               45

   Before Process Vacancy  D.I.C.E  After Process Vacancy  Enrolled Students  \
0                       2        0                      2                 43
1                       6        0                      6                 39
2                       0        0                      0                 45
3                       2        0                      2                 43
4                       2        0                      2                 43

   Median Bid  Min Bid            Instructor School/Department
0         0.0      0.0             GRACE FAN               SOA
1         0.0      0.0          CHARLES CHEN               SOA
2         0.0      0.0   CHARMAYNE HIGHFIELD               SOA
3         0.0      0.0   CHARMAYNE HIGHFIELD               SOA
4         0.0      0.0             GRACE FAN               SOA

Column Name: Term
Column Name: Session
Column Name: Bidding Window
Column Name: Course Code
Column Name: Description
Column Name: Section
Column Name: Vacancy
Column Name: Opening Vacancy
Column Name: Before Process Vacancy
Column Name: D.I.C.E
Column Name: After Process Vacancy
Column Name: Enrolled Students
Column Name: Median Bid
Column Name: Min Bid
Column Name: Instructor
Column Name: School/Department

In [40]:
# throw "Term" and "Session" as they are likely to be repeated
df = df.rename(columns={"Bidding Window":"Window","Course Code":"Code","Description":"ModName",
                        "Opening Vacancy":"Opening Vacancy",
               "Before Process Vacancy":"BProcessVacancy","D.I.C.E":"DICE",
                "After Process Vacancy":"AProcessVacancy","Enrolled Students":"Enrolled",
               "Median Bid":"Median","Min Bid":"Min","Instructor":"Prof",
               "School/Department":"School"}) 
df = df.drop(['Term','Session'],axis=1)
# replace column name
print(df.head())

              Window     Code               ModName Section  Vacancy  \
0  Round 2A Window 3  ACCT101  Financial Accounting      G1       45
1  Round 2A Window 3  ACCT101  Financial Accounting     G10       45
2  Round 2A Window 3  ACCT101  Financial Accounting     G11       45
3  Round 2A Window 3  ACCT101  Financial Accounting     G12       45
4  Round 2A Window 3  ACCT101  Financial Accounting      G2       45

   Opening Vacancy  BProcessVacancy  DICE  AProcessVacancy  Enrolled  Median  \
0               45                2     0                2        43     0.0
1               45                6     0                6        39     0.0
2               45                0     0                0        45     0.0
3               45                2     0                2        43     0.0
4               45                2     0                2        43     0.0

   Min                  Prof School
0  0.0             GRACE FAN    SOA
1  0.0          CHARLES CHEN    SOA
2  0.0   CHARMAYNE HIGHFIELD    SOA
3  0.0   CHARMAYNE HIGHFIELD    SOA
4  0.0             GRACE FAN    SOA

In [41]:
# get all IS mods price in round 1 window 1
# allISMods = df.query(["School == 'SIS'","Window == 'Round 1 Window 1'"])
# allISMods.head()
allISMods = df.loc[(df['School'] == 'SIS') & (df['Window'] == 'Round 1 Window 1'),["Code","ModName","Section","Prof","Median","Min"]]
allISMods.head()

,Code,ModName,Section,Prof,Median,Min
11647,COR-IS1702,Computational Thinking,G1,MOK HENG NGEE,32.39,24.97
11648,COR-IS1702,Computational Thinking,G2,CAO YIXIN,35.75,21.50
11649,COR-IS1702,Computational Thinking,G21,NGUYEN THIEN DUC,0.00,0.00
11650,COR-IS1702,Computational Thinking,G22,ASANKHAYA SHARMA,0.00,0.00
11651,COR-IS1702,Computational Thinking,G3,MAI ANH TIEN,13.42,13.42

In [62]:
# group by 
groupedMods = allISMods.groupby(["Code","ModName"])['Section','Median','Min']
# .agg(["Median","Min"])
# groupedMods.round(2).sort_values(by='Median', ascending=False)
for mod in groupedMods:
    print(" ")
    for section in mod:
        print(section)

('COR-IS1702', 'Computational Thinking')
      Section  Median    Min
11647      G1   32.39  24.97
11648      G2   35.75  21.50
11649     G21    0.00   0.00
11650     G22    0.00   0.00
11651      G3   13.42  13.42
11652      G4   17.51  15.02
11653      G5   10.10  10.10
11654      G6   20.50  10.11
11655      G7   12.89  11.00

('COR1305', 'Spreadsheet Modeling and Analytics')
      Section  Median    Min
11763      G1   21.00  10.05
11764      G2   30.00  10.00
11765      G3   45.68  25.69
11766      G4   42.22  30.03
11767      G5   45.54  22.22

('CS102', 'Programming Fundamentals II')
      Section  Median    Min
11911      G1   15.10  15.10
11912      G2    0.00   0.00
11913      G3   10.05  10.00
11914      G4   10.02  10.02

('CS105', 'Statistical Thinking for Data Science')
      Section  Median    Min
11915      G1   10.00  10.00
11916      G2   10.01  10.00
11917      G3   13.09  11.07
11918      G4   10.10  10.10

('CS106', 'Computer Hardware and Embedded Systems')
      Section  Median    Min
11919      G1   10.10  10.10
11920      G2   10.02  10.02
11921      G3    0.00   0.00
11922      G4   15.10  15.10

('CS202', 'Design and Analysis of Algorithms')
      Section  Median   Min
11923      G1   15.69  13.2
11924      G2   13.71  12.0
11925      G3   12.67  10.0

('CS205', 'Operating System Concepts with Android')
      Section  Median    Min
11926      G1   13.51  11.01
11927      G2   15.71  15.00
11928      G3   13.21  10.15

('CS206', 'Software Product Management')
      Section  Median    Min
11929      G1   15.00  12.89
11930      G2   15.45  10.71
11931      G3   20.31  16.83

('CS301', 'IT Solution Architecture(SMU-X)')
      Section  Median    Min
11932      G1    38.5  15.01

('CS420', 'Introduction to Artificial Intelligence')
      Section  Median    Min
11933      G1   14.42  10.00
11934      G2   12.00  10.00
11935      G3   17.45  14.89

('CS421', 'Principles of Machine Learning')
      Section  Median   Min
11936      G1   20.17  10.0

('CS424', 'Image Perception')
      Section  Median    Min
11937      G1   21.63  12.01
11938      G2   21.00  13.04

('CS426', 'Agent-based Modeling and Simulation')
      Section  Median   Min
11939      G1   15.74  10.0
11940      G2   19.19  10.1

('CS440', 'Foundations of Cybersecurity')
      Section  Median    Min
11941      G1   13.53  10.12
11942      G2   14.01  11.12
11943      G3   12.93  10.05
11944      G4   13.01  10.05

('CS441', 'Network Security')
      Section  Median    Min
11945      G1   17.81  11.71

('CS442', 'Data Security and Privacy')
      Section  Median    Min
11946      G1   18.65  13.01
11947      G2   23.45  11.00

('CS443', 'Software and Systems Security')
      Section  Median    Min
11948      G1    35.0  28.06

('CS445', 'Cyber Threat Intelligence')
      Section  Median    Min
11949      G1   37.39  25.69

('CS460', 'Foundations of Cyber-Physical Systems')
      Section  Median   Min
11950      G1    14.5  14.0

('CS460', 'Foundations of Cyber-Physical Systems(SMU-X)')
      Section  Median   Min
11951      G2   13.51  10.5

('CS461', 'Mobile & Pervasive Computing and Applications')
      Section  Median    Min
11952      G1   32.77  30.88
11953      G2   33.49  23.22

('CS462', 'Internet of Things: Technology and Applications(SMU-X)')
      Section  Median   Min
11954      G1   13.02  10.0

('CS471', 'Guided Research in Computer Science II')
      Section  Median  Min
11955      G1     0.0  0.0

('CS472', 'Guided Advanced Research in Computer Science')
      Section  Median  Min
11956      G1     0.0  0.0

('CS480', 'Computer Science Project Experience')
      Section  Median  Min
11958      G2     0.0  0.0

('CS480', 'Computer Science Project Experience(SMU-X)')
      Section  Median  Min
11957      G1     0.0  0.0

('CS490', 'Computer Science Work Study Elective')
      Section  Median  Min
11959      G1     0.0  0.0

('IS105', 'Business Data Management')
      Section  Median  Min
12083      G1     0.0  0.0
12084      G2     0.0  0.0
12085      G3     0.0  0.0
12086      G4     0.0  0.0
12087      G5     0.0  0.0

('IS111', 'Introduction to Programming')
      Section  Median    Min
12088      G1   13.20  10.55
12089      G2    0.00   0.00
12090      G3   14.13  12.17

('IS112', 'Data Management')
      Section  Median    Min
12091      G1   22.00  22.00
12092     G10    0.00   0.00
12093      G2   20.55  20.55
12094     G21   30.10  30.10
12095     G22    0.00   0.00
12096     G23    0.00   0.00
12097     G24    0.00   0.00
12098      G3   10.02  10.02
12099      G4   12.50  12.50
12100      G5   12.90  11.21
12101      G6   25.15  12.90
12102      G7   10.15  10.15
12103      G8    0.00   0.00
12104      G9    0.00   0.00

('IS113', 'Web Application Development I')
      Section  Median    Min
12105      G1   40.93  40.59
12106     G10    0.00   0.00
12107      G2    0.00   0.00
12108      G3   30.00  30.00
12109      G4   32.00  32.00
12110      G5    0.00   0.00
12111      G6    0.00   0.00
12112      G7   55.99  55.99
12113      G8   20.00  20.00
12114      G9    0.00   0.00

('IS213', 'Enterprise Solution Development')
      Section  Median    Min
12115      G1   16.89  13.00
12116     G10   30.68  24.02
12117      G2   21.00  10.00
12118      G3   22.00  20.22
12119      G4   18.77  17.11
12120      G5   16.56  10.00
12121      G6   17.51  11.28
12122      G7   15.42  10.00
12123      G8   40.00  37.69
12124      G9   39.99  36.24

('IS214', 'Enterprise Solution Management')
      Section  Median    Min
12125      G1   16.26  10.00
12126     G10   19.99  10.00
12127      G2   12.00  10.00
12128      G3   32.03  10.00
12129      G4   35.44  23.06
12130      G5   24.01  22.69
12131      G6   21.88  11.88
12132      G7   18.00  10.00
12133      G8   22.24  20.43
12134      G9   24.92  23.81

('IS215', 'Digital Business - Technologies and Transformation')
      Section  Median    Min
12135      G1   25.00  17.00
12136     G10   20.23  19.04
12137     G11   23.69  20.00
12138     G12   21.89  19.77
12139     G13   21.87  19.80
12140      G2   27.20  26.69
12141      G3   27.58  20.35
12142      G4   19.89  10.00
12143      G5   20.89  11.38
12144      G6   20.21  10.00
12145      G7   18.70  10.00
12146      G8   23.95  20.89
12147      G9   20.56  15.11

('IS217', 'Analytics Foundation')
      Section  Median    Min
12148      G1   15.30  12.00
12149      G2   15.94  10.00
12150      G3   12.34  10.00
12151      G4   12.12  10.00
12152      G5   13.24  10.02
12153      G6   12.65  10.77

('IS405', 'Technology Entrepreneurship Study Mission (Non-Asia)(USA)')
      Section  Median  Min
12154      G1     0.0  0.0

('IS415', 'Geospatial Analytics and Applications')
      Section  Median    Min
12155      G1   19.19  11.91

('IS419', 'Retail Banking and Mobile Technology')
      Section  Median    Min
12156      G1   12.45  10.50
12157      G2   16.84  10.01

('IS424', 'Data Mining and Business Analytics')
      Section  Median    Min
12158      G1   51.52  22.82
12159      G2   53.02  52.25

('IS425', 'Digital Transformation Strategy(SMU-X)')
      Section  Median   Min
12160      G1   56.01  51.0

('IS428', 'Visual Analytics for Business Intelligence')
      Section  Median    Min
12161      G1   54.85  52.00
12162      G2   50.89  21.65

('IS434', 'Social Analytics and Applications(SMU-X)')
      Section  Median    Min
12163      G1   40.79  28.05

('IS442', 'Object Oriented Programming(SMU-X)')
      Section  Median    Min
12164      G1   50.91  48.71
12165      G2   50.08  49.00

('IS444', 'Digital Banking Enterprise Architecture')
      Section  Median    Min
12166      G1   16.65  11.01
12167      G2   10.89  10.00

('IS445', 'Corporate Banking Technology')
      Section  Median   Min
12168      G1   21.78  10.0

('IS446', 'Managing Customer Relations with Analytics: Asian Insights')
      Section  Median    Min
12169      G1   53.06  35.00
12170      G2   40.09  12.11
12171      G3   54.24  52.10

('IS450', 'Text Mining and Language Processing')
      Section  Median   Min
12172      G1   47.51  18.0
12173      G2   48.11  26.0

('IS453', 'Financial Analytics')
      Section  Median    Min
12174      G1   33.88  28.98
12175      G2   40.23  31.31

('IS458', 'Cloud Management and Engineering')
      Section  Median    Min
12176      G1   50.01  42.29
12177      G2   41.00  10.00

('IS459', 'Big Data Architecture(SMU-X)')
      Section  Median    Min
12178      G1   78.39  69.22

('IS460', 'Machine Learning & Applications')
      Section  Median    Min
12179      G1   18.89  10.69

('IS461', 'AI Governance')
      Section  Median   Min
12180      G1   16.88  10.0

('IS462', 'Virtual Reality for Business(SMU-X)')
      Section  Median   Min
12181      G1    49.4  30.0

('IS470', 'Guided Research in Computing')
      Section  Median  Min
12182      G1     0.0  0.0

('IS471', 'Guided Research in Computing 2')
      Section  Median  Min
12183      G1     0.0  0.0

('IS472', 'Guided Advanced Research in Computing')
      Section  Median  Min
12184      G1     0.0  0.0

('IS483', 'IS/SMT Project Experience (Applications)(SMU-X)')
      Section  Median  Min
12185      G1     0.0  0.0
12186      G2     0.0  0.0
12187      G3     0.0  0.0
12188      G4     0.0  0.0
12189      G5     0.0  0.0
12190      G6     0.0  0.0
12191      G7     0.0  0.0
12192      G8     0.0  0.0

('IS484', 'IS Project Experience [FinTech]')
      Section  Median   Min
12193      G1    10.0  10.0
12194      G2    10.0  10.0

('IS485', 'IS Project Experience (Research)(SMU-X)')
      Section  Median  Min
12195      G1     0.0  0.0

('SMT112', 'Sustainable Digital Cities')
      Section  Median   Min
12521      G1   10.18  10.0

/var/folders/0y/v8qpzcw97kb4q0c34qdc6n100000gn/T/ipykernel_57947/2302751521.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  groupedMods = allISMods.groupby(["Code","ModName"])['Section','Median','Min']