In [1]:
# import data
# try 1 data set first
import pandas as pd
# can change the file name (refer to files folder)
df = pd.read_excel("./files/2022-23_T2.xlsx")

In [2]:
# check head
print(df.head())
print("")
# check if columns are there
for column in df.columns:
    print("Column Name:",column)

             Term                   Session     Bidding Window Course Code  \
0  2022-23 Term 1  Regular Academic Session  Round 2A Window 3     ACCT009
1  2022-23 Term 1  Regular Academic Session  Round 2A Window 3     ACCT101
2  2022-23 Term 1  Regular Academic Session  Round 2A Window 3     ACCT101
3  2022-23 Term 1  Regular Academic Session  Round 2A Window 3     ACCT101
4  2022-23 Term 1  Regular Academic Session  Round 2A Window 3     ACCT101

                                         Description Section  Vacancy  \
0  Overseas Project Experience (Accounting in Asi...      G1       25
1                               Financial Accounting      G1       45
2                               Financial Accounting     G10       45
3                               Financial Accounting     G11       45
4                               Financial Accounting     G12       45

   Opening Vacancy  Before Process Vacancy  D.I.C.E  After Process Vacancy  \
0               23                       2        0                      2
1               45                       2        0                      2
2               45                       4        0                      4
3               45                       4        0                      4
4               45                       2        0                      2

   Enrolled Students  Median Bid  Min Bid                  Instructor  \
0                 21         0.0      0.0   YUANTO KUSNADI, KEVIN LEE
1                 43         0.0      0.0             RICHARD CROWLEY
2                 41         0.0      0.0                DAVID SAMUEL
3                 41         0.0      0.0                DAVID SAMUEL
4                 43         0.0      0.0         CHARMAYNE HIGHFIELD

  School/Department
0               SOA
1               SOA
2               SOA
3               SOA
4               SOA

Column Name: Term
Column Name: Session
Column Name: Bidding Window
Column Name: Course Code
Column Name: Description
Column Name: Section
Column Name: Vacancy
Column Name: Opening Vacancy
Column Name: Before Process Vacancy
Column Name: D.I.C.E
Column Name: After Process Vacancy
Column Name: Enrolled Students
Column Name: Median Bid
Column Name: Min Bid
Column Name: Instructor
Column Name: School/Department

In [3]:
# throw "Term" and "Session" as they are likely to be repeated
df = df.rename(columns={"Bidding Window":"Window","Course Code":"Code","Description":"ModName",
                        "Opening Vacancy":"Opening Vacancy",
               "Before Process Vacancy":"BProcessVacancy","D.I.C.E":"DICE",
                "After Process Vacancy":"AProcessVacancy","Enrolled Students":"Enrolled",
               "Median Bid":"Median","Min Bid":"Min","Instructor":"Prof",
               "School/Department":"School"}) 
df = df.drop(['Term','Session'],axis=1)
# replace column name
print(df.head())

              Window     Code  \
0  Round 2A Window 3  ACCT009
1  Round 2A Window 3  ACCT101
2  Round 2A Window 3  ACCT101
3  Round 2A Window 3  ACCT101
4  Round 2A Window 3  ACCT101

                                             ModName Section  Vacancy  \
0  Overseas Project Experience (Accounting in Asi...      G1       25
1                               Financial Accounting      G1       45
2                               Financial Accounting     G10       45
3                               Financial Accounting     G11       45
4                               Financial Accounting     G12       45

   Opening Vacancy  BProcessVacancy  DICE  AProcessVacancy  Enrolled  Median  \
0               23                2     0                2        21     0.0
1               45                2     0                2        43     0.0
2               45                4     0                4        41     0.0
3               45                4     0                4        41     0.0
4               45                2     0                2        43     0.0

   Min                        Prof School
0  0.0   YUANTO KUSNADI, KEVIN LEE    SOA
1  0.0             RICHARD CROWLEY    SOA
2  0.0                DAVID SAMUEL    SOA
3  0.0                DAVID SAMUEL    SOA
4  0.0         CHARMAYNE HIGHFIELD    SOA

In [4]:
# get all IS mods price in round 1 window 1
# allISMods = df.query(["School == 'SIS'","Window == 'Round 1 Window 1'"])
# allISMods.head()
allISMods = df.loc[(df['School'] == 'SIS') & (df['Window'] == 'Round 1 Window 1'),["Code","ModName","Prof","Median","Min"]]
allISMods.head()

,Code,ModName,Prof,Median,Min
11821,COR-IS1702,Computational Thinking,MOK HENG NGEE,24.96,19.99
11822,COR-IS1702,Computational Thinking,SOON HUI SHIN VIVIEN,17.32,15.00
11823,COR-IS1702,Computational Thinking,NaN,0.00,0.00
11824,COR-IS1702,Computational Thinking,SOON HUI SHIN VIVIEN,0.00,0.00
11825,COR-IS1702,Computational Thinking,NaN,0.00,0.00

In [5]:
# group by 
groupedMods = allISMods.groupby(["Code","ModName"])['Median','Min'].mean()
# .agg(["Median","Min"])
groupedMods.round(2).sort_values(by='Median', ascending=True)

/var/folders/0y/v8qpzcw97kb4q0c34qdc6n100000gn/T/ipykernel_51431/2933276576.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  groupedMods = allISMods.groupby(["Code","ModName"])['Median','Min'].mean()

                                                               Median    Min
Code       ModName
SMT113     Sensors and IoT Programming                           0.00   0.00
SE101      Operating Systems and Networking                      0.00   0.00
IS490      Google Analytics Work-Study Elective                  0.00   0.00
IS483      IS/SMT Project Experience (Applications)(SMU-X)       0.00   0.00
IS455      Overseas Project Experience (Data Analytics in ...    0.00   0.00
IS404      Technology Entrepreneurship Study Mission (Asia...    0.00   0.00
IS215      Digital Business - Technologies and Transformation    0.00   0.00
IS105      Business Data Management                              0.00   0.00
IS111      Introduction to Programming                           3.51   3.18
CS101      Programming Fundamentals I                            5.52   5.28
CS104      Mathematical Foundations of Computing                 8.40   7.78
IS484      IS Project Experience [FinTech](SMU-X)               10.00  10.00
CS480      Computer Science Project Experience(SMU-X)           10.00  10.00
SMT203     Computational Social Science: Principles and Ap...   10.04  10.00
SMT481     Smart-City Operations Research                       10.31  10.00
SMT202     Analytics Applications for Smart Living(SMU-X)       11.50  10.16
COR-IS1702 Computational Thinking                               11.95   9.30
SMT201     Geographic Information Systems for Urban Planning    12.52  10.00
CS204      Interconnection of Cyber Physical Systems            13.04  10.25
CS103      Linear Algebra for Computing Applications            13.26  11.00
IS452      Blockchain Applications in Financial Services        13.56  10.41
CS201      Data Structures and Algorithms                       14.13  11.41
CS460      Foundations of Cyber-Physical Systems(SMU-X)         14.42  12.90
CS462      Internet of Things: Technology and Applications      14.76  10.52
CS444      Strategic Cybersecurity Management                   14.99  10.00
IS110      Information Systems and Innovation                   15.04  13.34
CS302      IT Solution Lifecycle Management                     15.06  10.56
IS419      Retail Banking and Mobile Technology                 15.20  10.30
IS113      Web Application Development I                        15.62  10.00
CS203      Collaborative Software Development(SMU-X)            15.63  11.34
IS217      Analytics Foundation                                 15.79  11.14
CS440      Foundations of Cybersecurity                         15.91  10.00
CS420      Introduction to Artificial Intelligence              16.78  11.50
CS301      IT Solution Architecture(SMU-X)                      16.96  11.00
IS460      Machine Learning & Applications                      17.44  10.00
IS211      Interaction Design and Prototyping                   18.13  12.93
IS457      Fairness in Socio-technical Systems                  18.42  10.00
IS444      Digital Banking Enterprise Architecture              18.72  16.51
CS425      Natural Language Communication                       19.97  11.68
CS422      Reasoning, Planning and Learning under Uncertainty   20.00  10.00
CS421      Principles of Machine Learning                       21.36  10.02
IS430      Digital Payments and Innovation                      22.44  15.54
IS210      Business Process Analysis & Solutioning              22.54  16.88
IS461      AI Governance                                        23.88  11.88
IS212      Software Project Management                          24.31  19.81
IS423      Financial Markets Processes and Technology           26.33  11.63
IS453      Financial Analytics                                  27.58  19.43
IS216      Web Application Development II                       29.14  21.46
IS434      Social Analytics and Applications(SMU-X)             29.84  10.40
CS443      Software and Systems Security                        30.81  28.88
IS412      Enterprise Business Solutions(SMU-X)                 40.73  38.00
COR1305    Spreadsheet Modeling and Analytics                   40.80  18.71
IS442      Object Oriented Programming(SMU-X)                   42.54  39.62
IS458      Cloud Management and Engineering                     44.46  33.81
IS425      Digital Transformation Strategy(SMU-X)               48.91  44.00
IS428      Visual Analytics for Business Intelligence           50.44  45.29
IS446      Managing Customer Relations with Analytics: Asi...   50.75  45.24
IS424      Data Mining and Business Analytics                   51.28  50.05
IS459      Big Data Architecture(SMU-X)                         60.00  50.00